### ISSUE TITLE
Установка регламентного запуска Doctests

### ISSUE THREAD

**Issue by amirismagilov** [amirismagilov/hw_distance_approximation#1]
#### Окружение:
OS: macOS 10.13.6
IDE: PyCharm CE
#### Не могу найти пункт Set Auto Test Delay в настройках консоли 
Последовательность действий:
* Создал автотест на функцию distance_approximation
* Запустил тест руками
* По аналогии с видео не смог найти как установить регламентный запуск тестов

![image](https://user-images.githubusercontent.com/47292284/52523855-11204980-2ca7-11e9-8e7a-fb5c65a233e5.png)

#### Прошу указать как настроить регламентный запуск тестов

**Comment by coursar** [comment]
Вы показываете экран в режиме дебага. Нужно в обычном режиме и там будет кнопка:
![screenshot](https://user-images.githubusercontent.com/3601892/52702548-7321cd00-2f8d-11e9-8d2c-1d34b002fcea.png)
